# Official PyTorch tutorial

## Tensors

This Jupyter notebook is self explanatory. No need to document or add more information.

In [1]:
import torch
import numpy as np

In [ ]:
# Create tensors directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print("Tensor from data:\n", x_data)

Tensor from data:
 tensor([[1, 2],
        [3, 4]])
Tensor from numpy array:
 tensor([[1, 2],
        [3, 4]])


In [3]:
# From a numpy array
np_array = np.array(data)
x_array = torch.from_numpy(np_array)
print("Tensor from numpy array:\n", x_array)

Tensor from numpy array:
 tensor([[1, 2],
        [3, 4]])


In [5]:
# From another tensor
x_ones = torch.ones_like(x_data)
print("Ones Tensor:\n", x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print("Random tensor:\n", x_rand)

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])
Random tensor:
 tensor([[0.5368, 0.2838],
        [0.2722, 0.5347]])


## Shape

In [6]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: \n{rand_tensor}\n")
print(f"Ones tensor: \n{ones_tensor}\n")
print(f"Zeros tensor: \n{zeros_tensor}\n")

Random tensor: 
tensor([[0.4037, 0.7645, 0.6248],
        [0.3162, 0.2664, 0.4790]])

Ones tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



## Tensor attributes

In [7]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: \n{tensor.shape}\n")
print(f"Datatype of tensor: \n{rand_tensor.dtype}\n")
print(f"Device tensor is stored on: \n{rand_tensor.device}\n")

Shape of tensor: 
torch.Size([3, 4])

Datatype of tensor: 
torch.float32

Device tensor is stored on: 
cpu



## Tensor Operations

In [9]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

In [10]:
# Standard numpy-like indexing and slicing
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
# Concatenate tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [12]:
## Multiplying tensors
# Compute element-wise product
print(f"tensor.mul(tensor)\n {tensor.mul(tensor)}\n")
# Alternative syntax
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor)
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
## Matrix multiplication

print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)}\n")
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [14]:
## In place operations: operations that have a _ suffix are in place.
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with numpy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other

In [17]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [18]:
# A change in the tensor reflects in the NumPy array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [19]:
# Numpy arrays to tensors
n = np.ones(5)
t = torch.from_numpy(n)

In [20]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
